### ISSUE TITLE
Question about Vue+Jupyter blog

### ISSUE THREAD

**Issue by ke-zhang-rd** [jitsejan/notebooks#1]
Hey,

I read your wonderful blog https://www.jitsejan.com/using-vuejs-in-jupyter-notebook.html. 
Since frontend design is far more richer in js community than python community, I really like your path that bring Vue to Jupyter. I believe this might be more and more popular.

However, when I try your notebook, I cannot find a way to load external css, specific vuetify related. I was wondering do you have nice solution to do this? Or would you be willing to update your blog with using vuetify? That would be great.

Thanks a lot!

**Comment by jitsejan** [comment]
I will look into this, but it has been a while. I started to work on this in the updated notebook for that blog post, but I did not get it to work yet. Once I have more time, I will give it another try! Let me know if you made progress too.

**Comment by jitsejan** [comment]
Obviously I did not have time to look into this yet. Curious to see if you got this working, otherwise I have finally some more time right now. Probably you have moved on since it has been more than a year. Apologies for the delay. Let me know if you got it working with Vuetify or with any other of the new frontend libraries.
